### ISSUE TITLE
Fixed auth problem for RStudio server 2021.09.2

### ISSUE THREAD

**Issue by hgputnam** [UCSF-CBI/c4-ondemand-interactive-apps#1]
@HenrikBengtsson - I just fixed the auth problem in OnDemand using what you just taught me on the other repo. Now that I understood the pam=auth script was being passed 'password', I realized that the OnDemand auth script was expecting 'PASSWORD'. Just changing the case on 2 lines fixed the whole thing. Woohoo!

**Comment by hgputnam** [comment]
TODOs -

Refactor the OnDemand app to use our new modules.

**Comment by HenrikBengtsson** [comment]
Hmm... looking at https://github.com/UCSF-CBI/c4-ondemand-interactive-apps/commit/bb6a0bb27cfcfa6578af702fa58b7587ab4b390e, I'd say that shouldn't matter.  There `password`/`PASSWORD` is just local variable.  AFAIU, it should work the same if you call it `donald_duck`.

**Comment by HenrikBengtsson** [comment]
Here's an example:

```sh
$ read -s -p "Password: " donald_duck  
Password: xxx
$ echo "donald_duck='${donald_duck}'"
donald_duck='foo'
```

**Comment by hgputnam** [comment]
Yup, I popped the champagne cork to early. Remember how I disabled auth yesterday to show you something? You can probably guess the rest...

OK, I see what you mean. In this case we have read -s which I *think* tells read to expect the input to come from STDIN which in this case is what comes out of the echo `"< password from form">|` pipe. Ok, so far it makes sense. But the generalized auth helper here: https://github.com/HenrikBengtsson/CBI-software/blob/master/CBI/rstudio-server/incl/pam-helper has `read -r`. So, how does read know the input is being piped into it? I would have expected something like `read -r - password`

**Comment by HenrikBengtsson** [comment]
https://github.com/UCSF-CBI/c4-ondemand-interactive-apps/blob/bbf34ecd94d20759b95ec13bb5272fdfb760cc39/Rstudio/view.html.erb

**Comment by HenrikBengtsson** [comment]
Typo in env var name in

https://github.com/UCSF-CBI/c4-ondemand-interactive-apps/blob/bbf34ecd94d20759b95ec13bb5272fdfb760cc39/Rstudio/view.html.erb

**Comment by hgputnam** [comment]
This is now obsolete thanks to rsc.
