### ISSUE TITLE
Stray `scancel.log` file in user's home directory

### ISSUE THREAD

**Issue by HenrikBengtsson** [UCSF-CBI/c4-ondemand-interactive-apps#16]
Not super important, but I just spotted this one:

```sh
[henrik@c4-log1 ~]$ more scancel.log 
Executing /usr/bin/scancel --signal=INT --full 434305 from c4-ondemand1
Exit status was 0
```

It's a very generic filename that doesn't hint it's related to OnDemand.  Maybe this can be written to `~/ondemand/logs/` instead, since `~/ondemand` is already created?

Also, I can imagine if a user runs multiple OnDemand tasks, this file will be overwritten constantly.

**Comment by hgputnam** [comment]
Leftover troubleshooting step I put in. This is controlled in the same file as #12 , removed the bin_override section.
