### ISSUE TITLE
OnDemand "Delete Session" button does not call a clean-up function.

### ISSUE THREAD

**Issue by hgputnam** [UCSF-CBI/c4-ondemand-interactive-apps#2]
Moving from sysadm issue.

**Comment by hgputnam** [comment]
This issue is for the RStudio app in our OnDemand setup. All of the OnDemand interactive apps have the same framework as outlined here:https://osc.github.io/ood-documentation/latest/app-development/interactive.html 

My understanding is, we can just write a ruby script called clean.sh.erb. This script gets rendered into a plain old shell script called clean.sh in the runtime directory that OnDemand creates for each new slurm session. The scripts within the framework (you can see them in this repo under the RStudio folder for instance) all combine together somehow to produce a runtime script called job_output.sh. This is the script that calls the before.sh, after.sh, and script.sh files. The problem here is, the big red button on the OnDemand web form that allows users to stop the session does NOT seem to call the clean function so the `rsc stop` command is not being issued when a user exits that way. I put a `rsc stop` line in script.sh,erb just ahead of the rserver command so that it will clean up a pre-existing session on that node. The problem is, what if the user submits a batch job that has command line rsc stuff in it? It would fail (and give a helpful error). So that is my concern. So long as the users are ONLY using OnDemand to access rsc it won't matter. But we could see a condition where other jobs fail because OnDemand didn't clean up.

**Comment by hgputnam** [comment]
My plea for help: https://discourse.osc.edu/t/can-the-delete-session-button-in-an-interactive-app-be-made-to-trigger-the-clean-up-function/1888

So far 17 views but no replies...

**Comment by HenrikBengtsson** [comment]
So, if I understand it correctly, you have a `template/clean.sh.erb` but it appears that OnDemand does not call it when someone clicks 'Delete Session'.  Is that correct?  Do you know for sure it's not calling that script?  Could you have it append some output to a file on the system as evidence it's running?

**Comment by hgputnam** [comment]
So, when we run a job this way it sets up some temp directories for each session. These are kept around for a time so we can troubleshoot stuff like this. There is an output.log associated with each job. I put an `echo Stop rsc` in the clean script so we can see if this gets called or not. 

### Test1

1. Carol launches RStudio app.
2. Carol logs in to RStudio (works).
3. Carol goes to an ssh terminal, ssh to the node RStudio is running on.
4. Carol now loads the module and types `rsc stop`.
5. The RStudio session is now gone.
6. I can see the following in output.log:
```
Script starting...
Waiting for RStudio Server to open port 7290...
RStudio Server is available on <http://c4-n12:7290>.  If you are running from a remote machine without direct access to c4-n12, you can use SSH port forwarding to access the RStudio Server at <http://127.0.0.1:8787> by running 'ssh -J carol@c4-log2.ucsf.edu -L 8787:c4-n12:7290 c4-n12' in a second terminal.  To stop the server, press Ctrl-C here, or run 'rsc stop' on c4-n12 in another shell.
Discovered RStudio Server listening on port 7290!
Generating connection YAML file...
/software/c4/cbi/software/rstudio-server-controller-0.1.2/bin/rsc: line 585: 58218 Terminated              rserver --config-file="${workdir}/rserver.conf"
Cleaning up...
Load rsc module
Stop rsc session
```

### Test2
1. Carol launches RStudio app.
2. Carol logs in to RStudio (works).
3. Carol clicks the "Delete Session" button.
4. output.log now looks like this:
```
Script starting...
Waiting for RStudio Server to open port 28009...
RStudio Server is available on <http://c4-n12:28009>.  If you are running from a remote machine without direct access to c4-n12, you can use SSH port forwarding to access the RStudio Server at <http://127.0.0.1:8787> by running 'ssh -J carol@c4-log2.ucsf.edu -L 8787:c4-n12:28009 c4-n12' in a second terminal.  To stop the server, press Ctrl-C here, or run 'rsc stop' on c4-n12 in another shell.
Discovered RStudio Server listening on port 28009!
Generating connection YAML file...
slurmstepd: error: *** JOB 405775 ON c4-n12 CANCELLED AT 2022-01-27T12:17:32 ***
```

**Comment by hgputnam** [comment]
So, Test1 is what I would *like* to happen, the clean script did it's job. It doesn't seem like it got called for the "Delete Session" action.

**Comment by hgputnam** [comment]
And if Carol tries to start a new RStudio, the output.log looks like this:

```
Script starting...
Waiting for RStudio Server to open port 58940...
ERROR: Another RStudio Server session of yours is already active on the system.  Please terminate that first, e.g. 'rsc stop'.  As a last resort, call 'pkill rserver; pkill rsession', remove lock file '/c4/home/carol/.config/rsc/pid.lock', and retry.
Traceback:
1: acquired_lock_file() on line #137 in /software/c4/cbi/software/rstudio-server-controller-0.1.2/bin/rsc
2: main() on line #567 in /software/c4/cbi/software/rstudio-server-controller-0.1.2/bin/rsc
Exiting (exit 1)
```

**Comment by HenrikBengtsson** [comment]
So, your Test 1 is just what you expect?  Are you saying you _don't_ get "Stop rsc session" in the log file?  Can you get the `template/clean.sh.erb` script to be called by OnDemand at all, e.g. other ways to shut down?  It looks like the goal is to get the `template/clean.sh.erb` script running.  When that works, then `rsc stop` should work.

Regardless, I suggest that you:

* Update to `module load CBI rstudio-server-controller/0.2.1`, or just `module load CBI rstudio-server-controller`.   That will give more informative `rsc stop` error messages, if that's the case.
* Use `rsc stop --debug`.
* You could even use `rsc start --debug --port=...` to see what happens at the end of that when it's terminates.

BTW, the debug and error messages are outputted to standard error. So, make sure OnDemand is logging stderr too (which it looks like it does from your last example).

**Comment by hgputnam** [comment]
From everything I have read the clean.sh is supposed to be called but is not when the Delete Session button is clicked. However, as you may have noticed, I am pretty far outside my comfort zone here. No one will ever confuse me with a web developer... I guess it might be a bug but I am highly suspicious that I am doing something wrong...

**Comment by HenrikBengtsson** [comment]
> From everything I have read the clean.sh is supposed ...

clean.sh or clean.sh.erb?

**Comment by hgputnam** [comment]
clean.sh.erb is "rendered" into clean.sh. https://osc.github.io/ood-documentation/latest/app-development/interactive/template.html There is no difference other than the .erb. I think the .sh.erb tells ruby to 'render' that into a shell script file. According to the above doc, clean.sh is supposed to be sourced into the main runtime script after the main script (the one that does the rserver command) is done executing. I guess I can't tell if that is happening but I do know the command is not being executed (the echo or the rsc stop).

**Comment by HenrikBengtsson** [comment]
https://osc.github.io/ood-documentation/latest/app-development/interactive/template.html#cleanup-hook mentions:

> Warning: If the batch script hits the maximum requested wall time, then this will not run. If this is an issue you are experiencing you may want to look into setting the timeout option under the batch_connect configuration feature in your submit.yml.erb.

That might be what's happening also when one hits 'Delete Session'.

If so, then we need to make sure `rsc start` cleans up after itself when terminating.  It's supposed to do that already now, but maybe the `kill` signal is "too strong" and the built-in EXIT trap in `rsc` is never run.  Using `rsc start --debug` should give some more clues.

**Comment by hgputnam** [comment]
I will try some of your suggestions tomorrow. I am currently in hardware hell. I set a new UCSF record for myself by installing 120 hard drives today... Plus a new storage and a new compute node. My knees need a break...

**Comment by HenrikBengtsson** [comment]
I'm still puzzled what's going on with Slurm, `scancel`, and how and when signals reaches the job script and when not.  But, with lots of trial and errors, it looks like:

```sh
scancel --signal=INT --full <job_id>
```

triggers the EXIT trap of `rsc start` such that it terminates any R sessions and removes the lock file.  If you can get OnDemand to do that when we click 'Delete Session', then we're at least solved it for OnDemand.

**Comment by HenrikBengtsson** [comment]
> I will try some of your suggestions tomorrow. I am currently in hardware hell. I set a new UCSF record for myself by installing 120 hard drives today... Plus a new storage and a new compute node. My knees need a break...

Wow!

**Comment by hgputnam** [comment]
OK, let me see if I can monkey with what that Delete button does...

**Comment by hgputnam** [comment]
OK we are in business. I had to zoom out and take a look at the overall OnDemand configuration. There is actually a file that lives on the OnDemand server called: # /etc/ood/config/clusters.d/c4yml. This file is responsible for configuring how slurm is integrated with OnDemand. The manual shows this example
```
# /etc/ood/config/clusters.d/my_cluster.yml
---
v2:
  metadata:
    title: "My Cluster"
  login:
    host: "my_cluster.my_center.edu"
  job:
    adapter: "slurm"
    cluster: "my_cluster"
    bin: "/path/to/slurm/bin"
    conf: "/path/to/slurm.conf"
    # bin_overrides:
      # sbatch: "/usr/local/bin/sbatch"
      # squeue: ""
      # scontrol: ""
      # scancel: ""
```

Notice the lovely bin_overides section! So, I can simply uncoment that stuf and set `scancel: "/usr/bin/scancel --signal=INT --full <job_id>"`

@HenrikBengtsson - we could also use a wrapper script for that, what would be your preference? This will only affect things run or canceled via OnDemand...

**Comment by hgputnam** [comment]
Never mind, it will have to be a wrapper. It is expecting a filename, not a command:

```
Details:

#<Errno::ENOENT: No such file or directory - /usr/bin/scancel --signal=INT --full>
```

**Comment by hgputnam** [comment]
The scancel portion of job cleanup is launched on the OnDemand node. I created /opt/slurm/scancel.sh on the OnDemand server. Put in an echo so I can be sure it is called later on.
```
#!/bin/bash

echo "Executing /usr/bin/scancel --signal=INT --full $1 from c4-ondemand1" > $HOME/scancel.log
/usr/bin/scancel --signal=INT --full $1
echo "Exit status was $?" >> $HOME/scancel.log
```
Submit a rsc job as user carol with this sbatch script:
```
#!/bin/bash

#SBATCH --time=08:00:00
#SBATCH --ntasks=4              # Number of CPUs
#SBATCH --mem=8gb               # Memory (GB)
#SBATCH --output=rsc.job.%j
#SBATCH --export=NONE


module load CBI rstudio-server-controller/0.2.1
rsc start --port=random
```

Now submit from c4-dev3:
```
[carol@c4-dev3 ~]$ sbatch rsc.sh
Submitted batch job 407966
```

User carol ssh to c4-n12 and loads the rsc module to check status:
```
[carol@c4-n12 ~]$ module load CBI rstudio-server-controller/0.2.1
[carol@c4-n12 ~]$ rsc status
rserver: running (pid 20853)
rsession: not running
[carol@c4-n12 ~]$ ls -l /c4/home/carol/.config/rsc/pid.lock
-rw-r--r-- 1 carol cbc 6 Jan 28 15:31 /c4/home/carol/.config/rsc/pid.lock
```

We also see the pid file is where it belongs

Now as user carol on the OnDemand server, execute the wrapper script:
`[carol@c4-ondemand1 ~]$  /opt/slurm/scancel.sh 407966`

Back to c4-n12:
```
carol@c4-n12 ~]$ rsc status
rserver: not running
rsession: not running
[carol@c4-n12 ~]$ ls -l /c4/home/carol/.config/rsc/pid.lock
ls: cannot access /c4/home/carol/.config/rsc/pid.lock: No such file or directory
```

So, we see everything working as expected. rsc stops the rserver and removes the pid file. We also note that the expected scancel.log file appears:
```
[carol@c4-n12 ~]$ cat scancel.log
Executing /usr/bin/scancel --signal=INT --full 407966 from c4-ondemand1
Exit status was 0
```

Ok, now we remove the above log file and start the next test:

Carol opens RStudio from OnDemand (uses rsc).

Check c4-n12, we see the lock file and rsc status as before.

Click Delete Session.

Check c4-n12:

rserver is stopped:
```[carol@c4-n12 ~]$ rsc status
rserver: not running
rsession: not running
```

scancel.log looks good:

```
[carol@c4-n12 ~]$ cat scancel.log
Executing /usr/bin/scancel --signal=INT --full 408048 from c4-ondemand1
Exit status was 0
```
But - the pid file is still there:

`[carol@c4-n12 ~]$ ls -l /c4/home/carol/.config/rsc/pid.lock`

So that is the current problem. I can not understand why this behaves differently when the delete button is used. It is clearly running the scancel command like we want...

**Comment by HenrikBengtsson** [comment]
I'll think more about this. I went down the rabbit hole yesterday with `rsc start` trying to figure how and when traps works/doesn't work.  I think the answer is in there somewhere, but I need to understand it better.  I learned a lot yesterday, but there's more to know.

**Comment by HenrikBengtsson** [comment]
BTW, could it be related who calls `scancel`?  You could add `echo "Called by $(who)"` to the `scancel.sh`, just so we log that too.

**Comment by hgputnam** [comment]
I will re-test, but I am pretty certain it is called by the user (carol in this case). The log file being produced is owned by carol...

**Comment by hgputnam** [comment]
I think you've fixed it:
```
[hputnam@c4-n12 ~]$ rsc status
WARNING: Detected a stray lock file (/c4/home/hputnam/.config/rsc/pid.lock). This file was removed, because there was no evidence that another instance was running on this system (no PID files for neither 'rserver' nor 'rsession' were found).
WARNING: Detected a stray PID file (/c4/home/hputnam/.config/rsc/rserver.pid). This file was removed, because it referred to a rserver process (PID 44104 on c4-n12) which is no longer running.
rserver: not running
rsession: not running
lock file: does not exist
```
I did the status after clicking the delete button.

**Comment by HenrikBengtsson** [comment]
> I think you've fixed it:

I wouldn't call "fixed it", but I made calls to `rsc` try to automatically clean up after `rsc startup` processes that fail to clean up after themselves.  But, yes, at least it makes the user's life easier.

**Comment by HenrikBengtsson** [comment]
Also, `rsc` can only do such cleanups when running on the same machine where `rsc startup` was running.  Otherwise you'll get:

```sh
[henrik@c4-dev1 ~]$ rsc status
rserver: unknown (pid 290700 on c4-n3, but current host is c4-dev1)
rsession: unknown (pid 290818 on c4-n3, but current host is c4-dev1)
lock file: exists (/c4/home/henrik/.config/rsc/pid.lock)
```

This is because it cannot check if those PIDs are still running unless it's done on the same machine as they're running.  To fix that, one would have to be able to query those PIDs over SSH.

**Comment by hgputnam** [comment]
Would rsc start in that condition: pid file exists but on a different host? I am limited in how much I can spend on this for right now. Finishing up some sever builds and preparing for tomorrow's outage...

**Comment by HenrikBengtsson** [comment]
> Would rsc start in that condition: pid file exists but on a different host? I am limited in how much I can spend on this for right now. Finishing up some sever builds and preparing for tomorrow's outage...

No, it won't;

```sh
[henrik@c4-dev1 ~]$ rsc start --port=uid
ERROR: henrik, another RStudio Server session of yours is already running on c4-n3 on this
system. See 'rsc status' for details. Please terminate that first, e.g. call 'rsc stop' 
from that machine. As a last resort, call 'pkill rserver; pkill rsession', remove lock
file '/c4/home/henrik/.config/rsc/pid.lock', and retry.
```

**Comment by HenrikBengtsson** [comment]
> ... Finishing up some sever builds and preparing for tomorrow's outage...

The outage is not tomorrow, but Wednesday (Feb 2), correct?

**Comment by HenrikBengtsson** [comment]
> > Would rsc start in that condition: pid file exists but on a different host? ...
> 
> No, it won't;
> 
> ```shell
> [henrik@c4-dev1 ~]$ rsc start --port=uid
> ERROR: henrik, another RStudio Server session of yours is already running on c4-n3 on this
> system. See 'rsc status' for details. Please terminate that first, e.g. call 'rsc stop' 
> from that machine. As a last resort, call 'pkill rserver; pkill rsession', remove lock
> file '/c4/home/henrik/.config/rsc/pid.lock', and retry.
> ```

BTW, OnDemand will also experience this problem as soon as the RStudio Server job ends up on another machine than before.

**Comment by HenrikBengtsson** [comment]
So, I just discovered that you, as the user, can access the session details, including all the OnDemand scripts, from the web interface.  Among those, I spotted the `job_script_content.sh` file, which contains the following among other things:

```sh
# Cleanliness is next to Godliness
clean_up () {
  echo "Cleaning up..."
  [[ -e "/c4/home/henrik/ondemand/data/sys/dashboard/batch_connect/sys/Rstudio/output/72d90535-e81a-422f-916d-99671f0d93fc/clean.sh" ]] && source "/c4/home/henrik/ondemand/data/sys/dashboard/batch_connect/sys/Rstudio/output/72d90535-e81a-422f-916d-99671f0d93fc/clean.sh"
  [[ ${SCRIPT_PID} ]] && pkill -P ${SCRIPT_PID} || :
  pkill -P $$
  exit ${1:-0}
}
```

the `clean_up()` function is called when the `script.sh` script finishes.

However, inspecting `/c4/home/henrik/ondemand/data/sys/dashboard/batch_connect/sys/Rstudio/output/72d90535-e81a-422f-916d-99671f0d93fc/`, **there are lots of files, but no `clean.sh` file!**;

```sh
$ ls -al /c4/home/henrik/ondemand/data/sys/dashboard/batch_connect/sys/Rstudio/output/72d90535-e81a-422f-916d-99671f0d93fc/
total 11
drwxr-xr-x  3 henrik cbc    9 Jan 31 14:21 .
drwxr-xr-x 10 henrik cbc    8 Jan 31 14:20 ..
-rwxr-xr-x  1 henrik cbc  308 Jan 31 14:20 after.sh
-rwxr-xr-x  1 henrik cbc  404 Jan 31 14:20 before.sh
drwxr-xr-x  2 henrik cbc    1 Jan 26 13:21 bin
-rw-------  1 henrik cbc   64 Jan 31 14:21 connection.yml
-rw-r--r--  1 henrik cbc 4374 Jan 31 14:20 job_script_content.sh
-rw-r--r--  1 henrik cbc  487 Jan 31 14:20 job_script_options.json
-rw-r--r--  1 henrik cbc 1212 Jan 31 14:21 output.log
-rwxr-xr-x  1 henrik cbc  254 Jan 31 14:20 script.sh
-rw-r--r--  1 henrik cbc  205 Jan 31 14:20 user_defined_context.json
```

I think that's the culprit.

**Comment by hgputnam** [comment]
So, the way OnDemand is set up, one does all the testing under a user account under $HOME/ondemand/dev. All of the monkeying I did with clean.sh is *just* in the carol account. To see that, you could log in to OnDemand as carol (see keepass). The app is no longer under the "Interactive Apps" section but is now under Develop-->Sandbox--Rstudio. So, carol has a copy of the repo but I am not merging that with the main because I don't want those apps deployed on the OnDemand server before they are ready. At some point, I want to talk to you about the best way to set up the Publishing of these apps. For the change I made earlier today I first pushed the changed to the repo, then git pull to the local repo on the OnDemand server. Once on the OnDemand server, I cp -R the Rstudio folder from the repo to the OnDemand server location. Seems sort of kludgy, hoping you have a better way. Remember, I am a not very crafty with github yet...

**Comment by HenrikBengtsson** [comment]
Oh, I see.

**Comment by HenrikBengtsson** [comment]
> > > Would rsc start in that condition: pid file exists but on a different host? ...
> > 
> > 
> > No, it won't;
> > ```shell
> > [henrik@c4-dev1 ~]$ rsc start --port=uid
> > ERROR: henrik, another RStudio Server session of yours is already running on c4-n3 on this
> > system. See 'rsc status' for details. Please terminate that first, e.g. call 'rsc stop' 
> > from that machine. As a last resort, call 'pkill rserver; pkill rsession', remove lock
> > file '/c4/home/henrik/.config/rsc/pid.lock', and retry.
> > ```
> 
> BTW, OnDemand will also experience this problem as soon as the RStudio Server job ends up on another machine than before.

As I wrote in Issue #3, `rsc` will now SSH into the machine where `rsc start` was launched to check if it's still running or not.  This means `rsc start` will automatically clean out any stray PID and lock files so that it can run.  This requires rsc 0.3.3 (https://github.com/UCSF-CBI/rstudio-server-controller/blob/main/NEWS.md), which is the new default on C4.

**Comment by HenrikBengtsson** [comment]
For got to say, I've tested this with few different scenarios mixing OnDemand and terminal calls to `rsc start` and `rsc status`.

**Comment by hgputnam** [comment]
Yeah, I forgot to post this but I tested rstudio launching on different nodes via OnDemand. The pid file got left behind from the first node and then it wouldn't start at all on the second node. It *does* start so long as you are on the *same* node but that doesn't help much. We need this to work on any node. I would like to talk to you about what the goal of the pid/lock files are. Was it to keep two sessions from running simultaneously and stepping on each other? Or was it more to protect the users local R stuff (packages, etc)? I can run from OnDemand just using the rstudio-server module from CBI but that just means I would be dropping the protections we get from rsc.

**Comment by HenrikBengtsson** [comment]
> Yeah, I forgot to post this but I tested rstudio launching on different nodes via OnDemand. The pid file got left behind from the first node and then it wouldn't start at all on the second node. It does start so long as you are on the same node but that doesn't help much. We need this to work on any node. 

Re-read my comment; this has been solved in rsc (>= 0.3.3)

> I  would like to talk to you about what the goal of the pid/lock files are. Was it to keep two sessions from running simultaneously and stepping on each other?

To prevent multiple session. If you don't have that protection, you'd end up seeing more and more stray `rsession` processes running on the system that people forget about.  The only way for them to terminate on the dev nodes is via an explicit `rsc stop`.  When launched in an interactive job, the scheduler will take care of `SIGQUIT`:ing it.

**Comment by hgputnam** [comment]
Ah, OK I will retest. OnDemand now calls the default rsc module. Makes sense about the stray sessions...

**Comment by hgputnam** [comment]
Retested and OnDemand is still a no go. 

### Test

- carol logs into ondemand and starts an RStudio session on cbc partition. Works fine (the first time).
- carol stops the session with the delete button.
- carol relaunches an RStudio session on the common partition.
- Rstudio never starts. Seeing this in the output.log:
```
Script starting...
Waiting for RStudio Server to open port 36217...
Host key verification failed.
ERROR: Stopping the RStudio Server can only be made from the machine (c4-n3) where it was started from
Traceback:
1: main() on line #905 in /software/c4/cbi/software/rstudio-server-controller-0.3.3/bin/rsc
Exiting (exit 1)
Host key verification failed.
ERROR: carol, another RStudio Server session of yours is already running on c4-n3 on this system. See 'rsc status' for details. Please terminate that first, e.g. call 'rsc stop' from that machine. As a last resort, call 'pkill rserver; pkill rsession', remove lock file '/c4/home/carol/.config/rsc/pid.lock', and retry.
Traceback:
1: acquire_lock_file() on line #136 in /software/c4/cbi/software/rstudio-server-controller-0.3.3/bin/rsc
2: main() on line #934 in /software/c4/cbi/software/rstudio-server-controller-0.3.3/bin/rsc
Exiting (exit 1)
```

One problem here is all the helpful directions that rsc gives to users to clean this up is invisible when using OnDemand. If I could figure out a way to have the rsc output sent back to the web page, at least the users could correct it themselves.

**Comment by HenrikBengtsson** [comment]
> Host key verification failed.

Argh... so, this is because:

```sh
[carol@c4-log1 ~]$ ssh c4-n3
The authenticity of host 'c4-n3 (10.10.10.13)' can't be established.
ECDSA key fingerprint is SHA256:4TljuD8eMQABXVuQEp9NIktgjwKw2Puzvw+Sa6uExWE.
ECDSA key fingerprint is MD5:cd:00:07:79:49:22:b7:e4:70:a8:45:2f:b1:0c:8f:aa.
Are you sure you want to continue connecting (yes/no)? 
```

That I don't think `rsc` can work around?  Is there any chance we can avoid this on the cluster?  We're already on C4, so why should we get that extra check when moving around to other C4 hosts?

**Comment by hgputnam** [comment]
That only happens the first time user connects to a particular host. I recently rebuilt one of the dev servers and did not want the users to get the even worse "someone is doing something nasty..." message. So, I wrote a small sed script to remove just that one entry from everyone's known_hosts file. Lets just say that, ahem, it did a little more deleting than I had planned (wiped all the entries).

Couple of options, you can call ssh differently from rsc: https://community.mellanox.com/s/article/howto-avoid-host-key-verification-when-using-ssh

Or, we could try to come up with a couple of scripts. Script 1 would dig the host key from each compute & dev node. Script2 would populate users's known_hosts. I am pretty sure so long as there is an entry with the correct host key, we never see that message.

**Comment by hgputnam** [comment]
I think option 1 might be best since option 2 would require updating everyone's known_hosts (with a better behaved sed script) each time we rebuild or add a host to the cluster.

**Comment by HenrikBengtsson** [comment]
See offline email.

**Comment by hgputnam** [comment]
Rolled out change discussed in email. Works beautifully now. I will get latest stuff into repo and publish. Then do some documentation next week and announce.

**Comment by HenrikBengtsson** [comment]
Awesome. Thxs.

**Comment by hgputnam** [comment]
Moot with new rsc setup. We turned off host key verification via /etc/ssh/ssh_config. Documented in ansible.
