### ISSUE TITLE
BUG: Can only request 256 GiB of local scratch (limit should be 2550 GiB)

### ISSUE THREAD

**Issue by HenrikBengtsson** [UCSF-CBI/c4-ondemand-interactive-apps#20]
# Issue

From [C4 Slack](https://ucsf-c4.slack.com/archives/C01M3CSSZT3/p1654653087665419) (2022-06-07T18:51):

> I wonder what is the reason to limit the memory and scratch space up to 256 GiB?  (although for scratch space it says 1 GiB - 2.5 TiB, but actually 256 GiB is the highest I can put there). I found in rare cases I would need up to 320 GB memory for some crazily large dataset.

# Troubleshooting

It's a cut'n'paste mistake; the `max` value for `slurm_scratch` is from `slurm_mem`:

https://github.com/UCSF-CBI/c4-ondemand-interactive-apps/blob/f506b4152376fb4ff77bb6e9ab6c3b5892353a1c/RStudio/form.yml#L41-L56

**Comment by hgputnam** [comment]
Corrected by making max value 2550
