### ISSUE TITLE
RStudio Server: Don't hard code the rstudio-server-controller version

### ISSUE THREAD

**Issue by HenrikBengtsson** [UCSF-CBI/c4-ondemand-interactive-apps#3]
While cleaning out several old versions of the `rstudio-server-controller` module, I noticed I broke OnDemand.  This is because:

https://github.com/UCSF-CBI/c4-ondemand-interactive-apps/blob/ae0e25e23b6c6ba0086a9abefad2f8265286aa18/Rstudio/template/script.sh.erb#L6

Can you please update that to 

```
module load CBI rstudio-server-controller
```

?  This is particularly important because otherwise OnDemand won't benefit from [all the improvement made to rstudio-server-controller](https://github.com/UCSF-CBI/rstudio-server-controller/blob/main/NEWS.md), including doing a better job cleaning up after itself.

**Comment by hgputnam** [comment]
Done - I had done so in my test environment but forgot the repo...

**Comment by HenrikBengtsson** [comment]
... but not yet deployed, correct?  Because launching the RStudio Server, I see:

```r
> Sys.getenv("PATH")
[1] "/software/c4/cbi/software/rstudio-server-controller-0.1.2/bin:...

> system("rsc status")
rserver: running (pid 290700)
rsession: running (pid 290818)
> system("rsc --version")
0.1.2
```

**Comment by HenrikBengtsson** [comment]
Seems to be working:

```sh
> system("rsc --version")
0.3.0
```

I've removed that old `rstudio-server-controller/0.1.2` module from the system.
