### ISSUE TITLE
RStudio Server: Drop `rsc stop`

### ISSUE THREAD

**Issue by HenrikBengtsson** [UCSF-CBI/c4-ondemand-interactive-apps#4]
The `rsc stop` in:

https://github.com/UCSF-CBI/c4-ondemand-interactive-apps/blob/7e9abf5b9334d6b5ea10c62e8568e24da4993a4d/Rstudio/template/script.sh.erb#L8-L9

will, not surprisingly, terminate any existing RStudio Server instances, which might not be what the user wants, e.g. click that button by mistake might kill a long-running R session.  If the user wants to stop another RStudio Server session, they have to explicitly click 'Delete Session' that session, or, if it's running from the terminal, they have to manually call `rsc stop` on the cluster.

I think this was added as a workaround to clean out stray lock files, etc.  That's now taken care of by `rsc start`.  With rsc (>= 0.3.3), it can also check PIDs on remote machines over SSH, so it should now handle all scenarios.

`rsc stop` can be dropped.

**Comment by HenrikBengtsson** [comment]
@hgputnam, don't forget this one too.

**Comment by hgputnam** [comment]
Already done.
