### ISSUE TITLE
GB -> GiB

### ISSUE THREAD

**Issue by HenrikBengtsson** [UCSF-CBI/c4-ondemand-interactive-apps#6]
https://github.com/UCSF-CBI/c4-ondemand-interactive-apps/blob/main/RStudio/form.yml uses GB i several places, but it should be GiB, which is not the same thing.

**Comment by hgputnam** [comment]
Pretty sure it is the same thing? You have to watch lowercase b  (bits) and uppercase B (bytes). Not aware of any other distinction. The only place I see the "i" (that I don't put in) is the Centos installer.

**Comment by HenrikBengtsson** [comment]
Nope, 1.0 GiB = 1.0 * 1024^3 bytes (IEC standard), whereas 1.0 GB = 1.0 * 1000^3 bytes (SI standard).  The difference between IEC and SI becomes quite big these days since we're working with so large files/objects.  I think this is important because we're working with scientists, and we shouldn't teach them to be sloppy about units.

(Trust me, I've tried to get R to get their things together for six years now; they use home-cooked 1.0 Gb (argh!) for this; https://github.com/HenrikBengtsson/Wishlist-for-R/issues/6)

> The only place I see the "i" (that I don't put in) is the Centos installer.

We want to use the IEC standard (i.e. KiB, MiB, GiB, TiB), because that is what Slurm is use (i.e. 1024-based units).  So, when we request/specify memory in <https://github.com/UCSF-CBI/c4-ondemand-interactive-apps/blob/main/RStudio/form.yml>, they should be IEC, cf. https://www.c4.ucsf.edu/scheduler/submit-jobs.html.

**Comment by hgputnam** [comment]
Wow, never knew about all that. I never thought anyone worked in other than powers of 2 and anytime someone said 1000 in connection with IT, I just assumed they really meant 1024. I guess the Centos guys know something I don't...

At any rate, I think I corrected them all.
