### ISSUE TITLE
Slurm: need --nodes=1

### ISSUE THREAD

**Issue by HenrikBengtsson** [UCSF-CBI/c4-ondemand-interactive-apps#7]
FYI, we need to specify `--nodes=1` to make sure Slurm allocated the job to a single machine. Without it, there's a risk that `--ntasks=n` of spread out across multiple machines.

https://www.c4.ucsf.edu/scheduler/submit-jobs.html#submit-a-script-to-run-in-batch-mode

**Comment by hgputnam** [comment]
I've been removing the Nodes field from the user form and hard-coding "N 1" in the submit code. I agree we ALWAYS want to restrict these interactive apps to a single node.
